# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backend/proto/market_data.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'backend/proto/market_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x62\x61\x63kend/proto/market_data.proto\x12\nmarketdata\"o\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\x03\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x0c\n\x04side\x18\x04 \x01(\x08\x12\x12\n\norder_type\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x01\"h\n\x05Trade\x12\x14\n\x0c\x62uy_order_id\x18\x01 \x01(\x03\x12\x15\n\rsell_order_id\x18\x02 \x01(\x03\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x11\n\ttimestamp\x18\x05 \x01(\x01\"1\n\x0eOrderBookLevel\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\x91\x01\n\x11OrderBookSnapshot\x12\x15\n\rinstrument_id\x18\x01 \x01(\t\x12(\n\x04\x62ids\x18\x02 \x03(\x0b\x32\x1a.marketdata.OrderBookLevel\x12(\n\x04\x61sks\x18\x03 \x03(\x0b\x32\x1a.marketdata.OrderBookLevel\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\"j\n\x0fOrderBookUpdate\x12\x15\n\rinstrument_id\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x0c\n\x04side\x18\x04 \x01(\x08\x12\x11\n\ttimestamp\x18\x05 \x01(\x01\",\n\x13SubscriptionRequest\x12\x15\n\rinstrument_id\x18\x01 \x01(\t\"\x82\x01\n\x12MarketDataResponse\x12\x31\n\x08snapshot\x18\x01 \x01(\x0b\x32\x1d.marketdata.OrderBookSnapshotH\x00\x12-\n\x06update\x18\x02 \x01(\x0b\x32\x1b.marketdata.OrderBookUpdateH\x00\x42\n\n\x08msg_type2o\n\x11MarketDataService\x12Z\n\x13SubscribeMarketData\x12\x1f.marketdata.SubscriptionRequest\x1a\x1e.marketdata.MarketDataResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend.proto.market_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=47
  _globals['_ORDER']._serialized_end=158
  _globals['_TRADE']._serialized_start=160
  _globals['_TRADE']._serialized_end=264
  _globals['_ORDERBOOKLEVEL']._serialized_start=266
  _globals['_ORDERBOOKLEVEL']._serialized_end=315
  _globals['_ORDERBOOKSNAPSHOT']._serialized_start=318
  _globals['_ORDERBOOKSNAPSHOT']._serialized_end=463
  _globals['_ORDERBOOKUPDATE']._serialized_start=465
  _globals['_ORDERBOOKUPDATE']._serialized_end=571
  _globals['_SUBSCRIPTIONREQUEST']._serialized_start=573
  _globals['_SUBSCRIPTIONREQUEST']._serialized_end=617
  _globals['_MARKETDATARESPONSE']._serialized_start=620
  _globals['_MARKETDATARESPONSE']._serialized_end=750
  _globals['_MARKETDATASERVICE']._serialized_start=752
  _globals['_MARKETDATASERVICE']._serialized_end=863
# @@protoc_insertion_point(module_scope)
