# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from backend.proto import market_data_pb2 as backend_dot_proto_dot_market__data__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in backend/proto/market_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketDataServiceStub(object):
    """Service definition for market data.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeMarketData = channel.unary_stream(
                '/marketdata.MarketDataService/SubscribeMarketData',
                request_serializer=backend_dot_proto_dot_market__data__pb2.SubscriptionRequest.SerializeToString,
                response_deserializer=backend_dot_proto_dot_market__data__pb2.MarketDataResponse.FromString,
                _registered_method=True)


class MarketDataServiceServicer(object):
    """Service definition for market data.
    """

    def SubscribeMarketData(self, request, context):
        """A server-streaming RPC. Client sends one request, server sends a stream of responses.
        The first message will be a snapshot, followed by incremental updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeMarketData': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeMarketData,
                    request_deserializer=backend_dot_proto_dot_market__data__pb2.SubscriptionRequest.FromString,
                    response_serializer=backend_dot_proto_dot_market__data__pb2.MarketDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketdata.MarketDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketdata.MarketDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketDataService(object):
    """Service definition for market data.
    """

    @staticmethod
    def SubscribeMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/marketdata.MarketDataService/SubscribeMarketData',
            backend_dot_proto_dot_market__data__pb2.SubscriptionRequest.SerializeToString,
            backend_dot_proto_dot_market__data__pb2.MarketDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
